apiVersion: v1
data:
  dbconn: 
  password: 
  username: 
  db_name: 
  bff_url: 
  backend_url: 
  frontend_url: 
  app_id_credentials: 
  app_id_sign_in: 
  crk_id: 
  kp_instance_id: 
  kms_url_secret: 
  API_KEY: 
  cert_pem: 
kind: Secret
metadata:
  name: cloud-fund-environment-secrets
type: Opaque
