apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "sgx-uninstaller.fullname" . }}
  annotations:
    "helm.sh/hook": post-delete
  labels:
{{ include "sgx-uninstaller.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sgx-uninstaller.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sgx-uninstaller.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        name: sgx-driver-uninstaller
        volumeMounts:
        - mountPath: /host
          name: test-volume
      volumes:
      - name: test-volume
        hostPath:
          # directory location on host
          path: /
