{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "sgx-installer.serviceAccountName" . }}
  labels:
{{ include "mychart.labels" . | indent 4 }}
{{- end -}}
