apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "sgx-installer.fullname" . }}
  labels:
{{ include "sgx-installer.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sgx-installer.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sgx-installer.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        name: sgx-driver-installer
        volumeMounts:
        - mountPath: /host
          name: test-volume
      nodeSelector:
        ibm-cloud.kubernetes.io/sgx-enabled: "true"
      serviceAccount: sgx-admin
      volumes:
      - name: test-volume
        hostPath:
          # directory location on host
          path: /
