apiVersion: v1
kind: Pod
metadata:
  name: cloud-fund-backend
  labels:
    app: cloud-fund-backend
spec:
  containers:
  - name: mariadb
    image: mariadb:latest
    ports:
    - containerPort: 3306
      hostPort: 3306
      name: mariadb
      protocol: TCP
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: password
    - name: MYSQL_DATABASE
      value: transactions_db
  - name: java
    image: us.icr.io/datashield-core/cloud-fund-backend
    ports:
    - containerPort: 8080
    env:
    - name: ENCRYPTION_KEY
      valueFrom:
        secretKeyRef:
          name: cloud-fund-environment-secrets
          key: encryption_key
    - name: SALT_VALUE
      valueFrom:
        secretKeyRef:
          name: cloud-fund-environment-secrets
          key: salt_value
  restartPolicy: OnFailure
